#version: "3.8"
#
#services:
#
#  rabbitmq:
#    image: rabbitmq:3-management-alpine
#    container_name: 'rabbitmq-acme-pay'
#    ports:
#      - 5672:5672
#      - 15672:15672
#    volumes:
#      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq
#      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
#networks:
#  rabbitmq:
#    driver: bridge

#version: '2'
#
#services:
#
#  zookeeper:
#    container_name: zookeeper
#    image: bitnami/zookeeper:latest
#    networks:
#      - "kafka-net"
#    ports:
#      - "2181:2181"
#    environment:
#      ALLOW_ANONYMOUS_LOGIN: "yes"
#
#  kafka:
#    container_name: kafka
#    image: bitnami/kafka:latest
#    networks:
#      - kafka-net
#    environment:
#      KAFKA_BROKER_ID: "1"
#      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
#      KAFKA_ADVERTISED_HOST_NAME: "localhost"
#      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
#      ALLOW_PLAINTEXT_LISTENER: "yes"
#      KAFKA_AUTO_CREATE_TOPIC_ENABLE: "true"
#    depends_on:
#      - zookeeper
#
#
#networks:
#  kafka-net:
#    driver: "bridge"

version: '2'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181


  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    networks:
      - "kafka-net"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

networks:
  kafka-net:
    driver: bridge