server:
  port: 8888

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
      - id: account-service
        uri: http://localhost:8081
        predicates:
        - Method=GET
        - Path=/api/v1/accounts/create-card/{document}